server:
  port: 8092
eureka:
  client:
    service-url:
      defaultZone: http://eureka/eureka
properties:
  URL: https://web.stanford.edu/class/archive/cs/cs109/cs109.1166/stuff/titanic.csv
  adultAgeCriteria: 16

spring:
  application:
    name: titanic-backend
  cache:
    type: redis
    cache-names: redis-cache
  data:
    redis:
      host: redis
      port: 6379
      password: parole
  datasource:
    url: jdbc:postgresql://db/postgres
    username: user
    password: password
    driverClassName: org.postgresql.Driver
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: validate
  liquibase:
    enabled: true
    default-schema: titanic
    change-log: classpath:db/changelog/db.changelog-master.xml
    contexts: development, production
    drop-first: false
logging:
  level:
    org.springframework: INFO
    org.pablos.backend: DEBUG
  logback:
    rollingpolicy:
      max-file-size: 10MB
      max-history: 5
  file:
    name: ./logs/${spring.application.name}.log